// Generated by CoffeeScript 1.3.3
(function() {

  describe("the backbone.event.one plugin", function() {
    var should;
    should = chai.should();
    beforeEach(function() {
      var _this;
      this.eventSpy = sinon.spy();
      this.filterSpy = sinon.spy();
      this.context = {};
      this.filterReturnValue = true;
      this.obj = _.extend({}, Backbone.Events);
      _this = this;
      return this.obj.one("test", this.eventSpy, this.context, function() {
        _this.filterSpy.apply(this, arguments);
        return _this.filterReturnValue;
      });
    });
    describe("the one method", function() {
      it("should be able to be extend", function() {
        var backboneObjNames, objName, _i, _len;
        Backbone.Events.one.should.be.a("Function");
        backboneObjNames = ["Model", "Collection", "View", "Router", "History"];
        for (_i = 0, _len = backboneObjNames.length; _i < _len; _i++) {
          objName = backboneObjNames[_i];
          (new Backbone[objName])["one"].should.be.a("Function");
        }
        return _.extend({}, Backbone.Events)["one"].should.be.a("Function");
      });
      return it("should be work", function() {
        this.obj.trigger("test");
        this.obj.trigger("test");
        return this.eventSpy.calledOnce.should.be["true"];
      });
    });
    describe("the whenFilter", function() {
      it("should make event ignored if return false", function() {
        this.filterReturnValue = false;
        this.obj.trigger("test");
        this.eventSpy.called.should.be["false"];
        return this.filterSpy.calledOnce.should.be["true"];
      });
      it("should make event ignored if return false like value", function() {
        this.filterReturnValue = "";
        this.obj.trigger("test");
        this.eventSpy.called.should.be["false"];
        return this.filterSpy.calledOnce.should.be["true"];
      });
      it("should be called", function() {
        this.obj.trigger("test");
        return this.filterSpy.calledOnce.should.be["true"];
      });
      it("should called on context", function() {
        this.obj.trigger("test");
        return this.filterSpy.calledOn(this.context).should.be["true"];
      });
      return it("should get arguments passed in", function() {
        this.obj.trigger("test", "some", "args");
        return this.filterSpy.withArgs("some", "args").calledOnce.should.be["true"];
      });
    });
    return describe("the handler argument", function() {
      it("should be work", function() {
        this.obj.trigger("test", "some", "args");
        return this.eventSpy.withArgs("some", "args").calledOnce.should.be["true"];
      });
      it("should called on context", function() {
        this.obj.trigger("test");
        return this.eventSpy.calledOn(this.context).should.be["true"];
      });
      return it("should get arguments passed in", function() {
        this.obj.trigger("test", "some", "args");
        return this.eventSpy.withArgs("some", "args").calledOnce.should.be["true"];
      });
    });
  });

}).call(this);
